spring.application.name=EmpManagment
spring.datasource.url=jdbc:postgresql://localhost:5432/EmpManagementDB
spring.datasource.username=postgres
spring.datasource.password=WorkLife@1212
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.security.user.name=shivani
#spring.security.user.password=1234